//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDB_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class data1
    {
        public int id { get; set; }
        public Nullable<int> value1 { get; set; }
        public Nullable<int> value2 { get; set; }
    }
}
