//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDB_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dblog
    {
        public int idLog { get; set; }
        public string action { get; set; }
        public string table { get; set; }
        public int count { get; set; }
        public System.DateTime time { get; set; }
    }
}
