<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDB_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public Measurement()
        {
            this.Points = new HashSet<Point>();
        }
    
        public int idMeasurement { get; set; }
        public string serialNumberDevice { get; set; }
        public int idMtype { get; set; }
        public string description { get; set; }
        public string unit { get; set; }
        public int date { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual ICollection<Point> Points { get; set; }
        public virtual MType MType { get; set; }
    }
}
=======
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDB_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public Measurement()
        {
            this.Points = new HashSet<Point>();
        }
    
        public int idMeasurement { get; set; }
        public string serialNumberDevice { get; set; }
        public int idMtype { get; set; }
        public string description { get; set; }
        public string unit { get; set; }
        public int date { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual ICollection<Point> Points { get; set; }
        public virtual MType MType { get; set; }
    }
}
>>>>>>> b1419d96909f898cc2d2f557dda09b2de6ed0afe
