//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDB_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class MType
    {
        public MType()
        {
            this.Measurements = new HashSet<Measurement>();
        }
    
        public int idType { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Measurement> Measurements { get; set; }
    }
}
