//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDB_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HovnoEntities : DbContext
    {
        public HovnoEntities()
            : base("name=HovnoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bigdata> bigdatas { get; set; }
        public virtual DbSet<data1> data1 { get; set; }
        public virtual DbSet<data2> data2 { get; set; }
        public virtual DbSet<data3> data3 { get; set; }
    }
}
