//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDB_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public System.DateTime date { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public double value1 { get; set; }
        public double value2 { get; set; }
        public double difference { get; set; }
        public string serialNumber { get; set; }
    }
}
